# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('p', models.CharField(max_length=200, verbose_name='Prime number P')),
                ('q', models.CharField(max_length=200, verbose_name='Prime number Q')),
                ('n', models.CharField(max_length=200, verbose_name='Number N')),
                ('e', models.CharField(max_length=200, verbose_name='Public key')),
                ('d', models.CharField(max_length=200, verbose_name='Private key')),
                ('f', models.CharField(max_length=200, verbose_name='Number f')),
                ('public_key', models.CharField(max_length=200, verbose_name='Public key')),
                ('private_key', models.CharField(max_length=200, verbose_name='Private key')),
                ('a1', models.CharField(max_length=200, verbose_name='First number')),
                ('b1', models.CharField(max_length=200, verbose_name='Second number')),
                ('a2', models.CharField(max_length=200, verbose_name='Encrypted first number')),
                ('b2', models.CharField(max_length=200, verbose_name='Encrypted second number')),
                ('a1b1', models.CharField(max_length=200, verbose_name='Multiples of two numbers')),
                ('a2b2', models.CharField(max_length=200, verbose_name='Multiples of encrypted two numbers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
