# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsa',
            name='a1b1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Multiples of two numbers'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='a2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Encrypted first number'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='a2b2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Multiples of encrypted two numbers'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='b2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Encrypted second number'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='d',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Private key'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='f',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Number F'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='n',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Number N'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='private_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Private key'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='public_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Public key'),
        ),
    ]
