# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20160530_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsa',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
