# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('algorithm', '0003_auto_20160530_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sezar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('a', models.CharField(max_length=200, verbose_name='First word')),
                ('b', models.CharField(max_length=200, verbose_name='second word')),
                ('k', models.CharField(max_length=200, verbose_name='Key')),
                ('ab', models.CharField(blank=True, max_length=200, null=True, verbose_name='Multiples of two word')),
                ('a1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encrypted first word')),
                ('b1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encrypted second word')),
                ('a1b1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Addition of encrypted two words')),
                ('ba', models.CharField(blank=True, max_length=200, null=True, verbose_name='Decrypt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
