# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_paillier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsa',
            name='ba',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Decrypt'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='d',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Private number D'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='e',
            field=models.CharField(max_length=200, verbose_name='Public number E'),
        ),
    ]
