# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_auto_20160531_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsa',
            name='text',
        ),
        migrations.AlterField(
            model_name='sezar',
            name='ab',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Addition of two word'),
        ),
    ]
